### ISSUE TITLE
compatibility issues with Matlab R2016b version

### ISSUE THREAD

**Issue by ASM3** [ethz-asl/fw_px4_plottools#2]
It seems as the script has some compatibility issues with the Matlab R2016b version. This is probably caused due to the string usage. It needs to be cleaned up for the 2016b version or to be decided whether this script should supports only Matlab 2017b version.

**Comment by acfloria** [comment]
I actually have Matlab R2017a. The reason why it currently does not work for older versions is that they added in that release the ability to define strings in the following way: `"text"`

@ASM3 is upgrading to R2017a an option.
If not could you try if the following works: `string('text')`
For testing you can remove all but one topic from the `setupTopics` function.

**Comment by mantelt** [comment]
Team decision: Use >=2016b
