### ISSUE TITLE
kml image splitted to many flight sections

### ISSUE THREAD

**Issue by ASM3** [ethz-asl/fw_px4_plottools#4]
Why the kml image is splitted to so many flight sections?

![image](https://user-images.githubusercontent.com/3127009/32734802-52fb2de4-c893-11e7-9d9a-cea64213b4da.png)

**Comment by acfloria** [comment]
In the default mode the path is colored by the control mode. During that flight the pilot switched the control mode multiple times, that is why you have multiple segments. You can change it to one single path by changing the corresponding [parameter](https://github.com/ethz-asl/fw_px4_plottools/blob/master/01_draw_functions/DisplayPX4LogData.m#L48) in the DisplayPX4LogData.m file.
